name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Step to set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Step to restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step to build the .NET project
    - name: Build
      run: dotnet build --no-restore

    # Step to run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Step to install Postman CLI on Ubuntu
    - name: Install Postman CLI
      run: |
        curl -L https://dl-cli.pstmn.io/install/linux64.sh | sh

    # Step to login to Postman CLI with API Key
    - name: Login to Postman CLI
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: postman login --with-api-key $POSTMAN_API_KEY

    # Step to run Postman collection tests
    - name: Run API tests
      run: |
        postman collection run "${{ github.workspace }}/postman/collections/SalesCollection.json"
